# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Navigate panes using vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind f resize-pane -Z

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy Mode with Vi bindings
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Paste buffer
# bind p paste-buffer

# switch to last active window
bind l last-window
