# Statusline Lengths
set-option -g status on
set-option -g status-interval 5
set-option -g status-justify centre
set -g status-right-length 100
set -g status-left-length 100

# Left Side — Nothing (Pure Minimalist)
set -g status-left "#{E:@catppuccin_status_session}"

# Right Side — Modular Catppuccin Goodness
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
