# Load modular configs
run-shell ~/.tmux/plugins/tpm/tpm

source-file ~/.dotfiles/tmux/conf.d/options.conf
source-file ~/.dotfiles/tmux/conf.d/keybindings.conf
source-file ~/.dotfiles/tmux/conf.d/statusbar.conf
source-file ~/.dotfiles/tmux/conf.d/plugins.conf
